# This item can safely be changed without old teleporter items breaking.
teleporter:
  # If you change the type from BEACON, the plugin will stop working.
  # Install Nexo for custom block support, and then add the TELEPORTER mechanic to the blocks
  # you want to act as teleporters.
  type: BEACON
  metadata:
    displayName: <light_purple>Teleporter
    lore:
      - "<gray>Berembert's grand invention!"
      - "<gray>Jumping, sends you to the above teleporter"
      - "<gray>Sneaking, sends you to the below teleporter"
      - "<gray>Punching, sends you to the ahead teleporter"
teleported: "<aqua><b>You have been teleported!"
sidewaysTeleportError: "<red><b>ERROR</b>: <gray>The teleporter you are aiming at is too far away. It needs to be under 90 blocks away!"