name: EnchantedTeleporters
version: '1.0-SNAPSHOT'
main: me.xemor.enchantedTeleporters.EnchantedTeleporters
api-version: '1.21'
authors: [ Xemor_ ]
folia-supported: true
libraries:
  - "com.fasterxml.jackson.core:jackson-core:2.18.0"
  - "com.fasterxml.jackson.core:jackson-databind:2.18.2"
  - "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.7.0"